name: OnPullRequest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false    

jobs:
  test_linux:
    runs-on: [self-hosted, Linux]

    steps:
    - uses: actions/checkout@v3
            
    - name: 'Build and install package'
      run: | 
        git submodule update --init --recursive
        python3 -m pip install -r requirements.txt
        python3 -m pip install . --verbose  

    - name: 'Run tests'
      run: |
        cd tests
        python3 -m unittest discover .